name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install asdf
        uses: asdf-vm/actions/setup@v2

      - name: Install tools
        run: |
          asdf plugin-add nodejs
          asdf install

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: Generate release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
